Repo Hash (Nightly Test):     [92d5d7d]
Repo Hash (Cloudformation):   [f15d144]
Nightly Test in the unity-cm account
Stack Name: [unity-cs-nightly-management-console]
Stack Status (Final): [CREATE_COMPLETE]
Stack Creation Time: [420 seconds] - PASS
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.4.3, pluggy-1.3.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/ubuntu/unity-cs-infra/nightly_tests
collecting ... collected 14 items

test_selenium_mc.py::test_navigate_to_mc_console PASSED                  [  7%]
test_selenium_mc.py::test_bootstrap_process_status PASSED                [ 14%]
test_selenium_mc.py::test_initiate_core_setup PASSED                     [ 21%]
test_selenium_mc.py::test_core_setup_save_btn PASSED                     [ 28%]
test_selenium_mc.py::test_click_install_EKS_btn ERROR                    [ 35%]
test_selenium_mc.py::test_EKS_module_name FAILED                         [ 42%]
test_selenium_mc.py::test_EKS_module_branch FAILED                       [ 50%]
test_selenium_mc.py::test_click_EKS_install_btns FAILED                  [ 57%]
test_selenium_mc.py::test_grab_terminal_output_EKS FAILED                [ 64%]
test_selenium_mc.py::test_click_install_SPS_btn PASSED                   [ 71%]
test_selenium_mc.py::test_SPS_module_name PASSED                         [ 78%]
test_selenium_mc.py::test_SPS_module_branch PASSED                       [ 85%]
test_selenium_mc.py::test_click_SPS_install_btns PASSED                  [ 92%]
test_selenium_mc.py::test_grab_terminal_output_SPS FAILED                [100%]

==================================== ERRORS ====================================
_________________ ERROR at setup of test_click_install_EKS_btn _________________
test_selenium_mc.py:133: in test_navigate_to_marketplace
    go_button = WebDriverWait(driver, 20).until(
../../.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:101: in until
    raise TimeoutException(message, screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E   Stacktrace:
E   #0 0x561bd80c0f83 <unknown>
E   #1 0x561bd7d79cf7 <unknown>
E   #2 0x561bd7dc999e <unknown>
E   #3 0x561bd7dc9aa1 <unknown>
E   #4 0x561bd7e14d64 <unknown>
E   #5 0x561bd7df30dd <unknown>
E   #6 0x561bd7e12006 <unknown>
E   #7 0x561bd7df2e53 <unknown>
E   #8 0x561bd7dbadd4 <unknown>
E   #9 0x561bd7dbc1de <unknown>
E   #10 0x561bd8085531 <unknown>
E   #11 0x561bd8089455 <unknown>
E   #12 0x561bd8071f55 <unknown>
E   #13 0x561bd808a0ef <unknown>
E   #14 0x561bd805599f <unknown>
E   #15 0x561bd80ae008 <unknown>
E   #16 0x561bd80ae1d7 <unknown>
E   #17 0x561bd80c0124 <unknown>
E   #18 0x7ff4a6514ac3 <unknown>

During handling of the above exception, another exception occurred:
test_selenium_mc.py:142: in test_navigate_to_marketplace
    raise Exception("Failed to navigate to the marketplace - either the button was not clickable or the URL did not change as expected.")
E   Exception: Failed to navigate to the marketplace - either the button was not clickable or the URL did not change as expected.
=================================== FAILURES ===================================
_____________________________ test_EKS_module_name _____________________________
test_selenium_mc.py:174: in test_EKS_module_name
    text_box = WebDriverWait(driver, 10).until(
../../.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:101: in until
    raise TimeoutException(message, screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E   Stacktrace:
E   #0 0x561bd80c0f83 <unknown>
E   #1 0x561bd7d79cf7 <unknown>
E   #2 0x561bd7dc999e <unknown>
E   #3 0x561bd7dc9aa1 <unknown>
E   #4 0x561bd7e14d64 <unknown>
E   #5 0x561bd7df30dd <unknown>
E   #6 0x561bd7e12006 <unknown>
E   #7 0x561bd7df2e53 <unknown>
E   #8 0x561bd7dbadd4 <unknown>
E   #9 0x561bd7dbc1de <unknown>
E   #10 0x561bd8085531 <unknown>
E   #11 0x561bd8089455 <unknown>
E   #12 0x561bd8071f55 <unknown>
E   #13 0x561bd808a0ef <unknown>
E   #14 0x561bd805599f <unknown>
E   #15 0x561bd80ae008 <unknown>
E   #16 0x561bd80ae1d7 <unknown>
E   #17 0x561bd80c0124 <unknown>
E   #18 0x7ff4a6514ac3 <unknown>

During handling of the above exception, another exception occurred:
test_selenium_mc.py:183: in test_EKS_module_name
    raise Exception(f"Failed to find or interact with the specified element (ID: {element_id}).")
E   Exception: Failed to find or interact with the specified element (ID: name).
____________________________ test_EKS_module_branch ____________________________
test_selenium_mc.py:195: in test_EKS_module_branch
    next_button = WebDriverWait(driver, 10).until(
../../.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:101: in until
    raise TimeoutException(message, screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E   Stacktrace:
E   #0 0x561bd80c0f83 <unknown>
E   #1 0x561bd7d79cf7 <unknown>
E   #2 0x561bd7dc999e <unknown>
E   #3 0x561bd7dc9aa1 <unknown>
E   #4 0x561bd7e14d64 <unknown>
E   #5 0x561bd7df30dd <unknown>
E   #6 0x561bd7e12006 <unknown>
E   #7 0x561bd7df2e53 <unknown>
E   #8 0x561bd7dbadd4 <unknown>
E   #9 0x561bd7dbc1de <unknown>
E   #10 0x561bd8085531 <unknown>
E   #11 0x561bd8089455 <unknown>
E   #12 0x561bd8071f55 <unknown>
E   #13 0x561bd808a0ef <unknown>
E   #14 0x561bd805599f <unknown>
E   #15 0x561bd80ae008 <unknown>
E   #16 0x561bd80ae1d7 <unknown>
E   #17 0x561bd80c0124 <unknown>
E   #18 0x7ff4a6514ac3 <unknown>

During handling of the above exception, another exception occurred:
test_selenium_mc.py:208: in test_EKS_module_branch
    raise Exception(f"Textbox for branch name (ID: {element_id}) not found.")
E   Exception: Textbox for branch name (ID: branch) not found.
_________________________ test_click_EKS_install_btns __________________________
test_selenium_mc.py:219: in test_click_EKS_install_btns
    next_button = WebDriverWait(driver, 10).until(
../../.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:101: in until
    raise TimeoutException(message, screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E   Stacktrace:
E   #0 0x561bd80c0f83 <unknown>
E   #1 0x561bd7d79cf7 <unknown>
E   #2 0x561bd7dc999e <unknown>
E   #3 0x561bd7dc9aa1 <unknown>
E   #4 0x561bd7e14d64 <unknown>
E   #5 0x561bd7df30dd <unknown>
E   #6 0x561bd7e12006 <unknown>
E   #7 0x561bd7df2e53 <unknown>
E   #8 0x561bd7dbadd4 <unknown>
E   #9 0x561bd7dbc1de <unknown>
E   #10 0x561bd8085531 <unknown>
E   #11 0x561bd8089455 <unknown>
E   #12 0x561bd8071f55 <unknown>
E   #13 0x561bd808a0ef <unknown>
E   #14 0x561bd805599f <unknown>
E   #15 0x561bd80ae008 <unknown>
E   #16 0x561bd80ae1d7 <unknown>
E   #17 0x561bd80c0124 <unknown>
E   #18 0x7ff4a6514ac3 <unknown>

During handling of the above exception, another exception occurred:
test_selenium_mc.py:240: in test_click_EKS_install_btns
    raise Exception(f"Failed to find or click the first button (class: {next_button_class}).")
E   NameError: name 'next_button_class' is not defined
________________________ test_grab_terminal_output_EKS _________________________
test_selenium_mc.py:252: in test_grab_terminal_output_EKS
    terminal_output_element = WebDriverWait(driver, 10).until(
../../.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:101: in until
    raise TimeoutException(message, screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E   Stacktrace:
E   #0 0x561bd80c0f83 <unknown>
E   #1 0x561bd7d79cf7 <unknown>
E   #2 0x561bd7dc999e <unknown>
E   #3 0x561bd7dc9aa1 <unknown>
E   #4 0x561bd7e14d64 <unknown>
E   #5 0x561bd7df30dd <unknown>
E   #6 0x561bd7e12006 <unknown>
E   #7 0x561bd7df2e53 <unknown>
E   #8 0x561bd7dbadd4 <unknown>
E   #9 0x561bd7dbc1de <unknown>
E   #10 0x561bd8085531 <unknown>
E   #11 0x561bd8089455 <unknown>
E   #12 0x561bd8071f55 <unknown>
E   #13 0x561bd808a0ef <unknown>
E   #14 0x561bd805599f <unknown>
E   #15 0x561bd80ae008 <unknown>
E   #16 0x561bd80ae1d7 <unknown>
E   #17 0x561bd80c0124 <unknown>
E   #18 0x7ff4a6514ac3 <unknown>

During handling of the above exception, another exception occurred:
test_selenium_mc.py:256: in test_grab_terminal_output_EKS
    raise Exception("Failed to find or load the terminal output element within the specified time.")
E   Exception: Failed to find or load the terminal output element within the specified time.
________________________ test_grab_terminal_output_SPS _________________________
test_selenium_mc.py:381: in test_grab_terminal_output_SPS
    assert "Error" in output_text.lower(), "Success not found in terminal output"
E   AssertionError: Success not found in terminal output
E   assert 'Error' in '\n\nundefined\n\n\nundefined\nundefined\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
E    +  where '\n\nundefined\n\n\nundefined\nundefined\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' = <built-in method lower of str object at 0x7fe6defa5f60>()
E    +    where <built-in method lower of str object at 0x7fe6defa5f60> = '\n\nundefined\n\n\nundefined\nundefined\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'.lower
=========================== short test summary info ============================
FAILED test_selenium_mc.py::test_EKS_module_name - Exception: Failed to find ...
FAILED test_selenium_mc.py::test_EKS_module_branch - Exception: Textbox for b...
FAILED test_selenium_mc.py::test_click_EKS_install_btns - NameError: name 'ne...
FAILED test_selenium_mc.py::test_grab_terminal_output_EKS - Exception: Failed...
FAILED test_selenium_mc.py::test_grab_terminal_output_SPS - AssertionError: S...
ERROR test_selenium_mc.py::test_click_install_EKS_btn - Exception: Failed to ...
=============== 5 failed, 8 passed, 1 error in 93.17s (0:01:33) ================
